name: Build

on:
  workflow_dispatch:
  workflow_call:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install npm dependencies
        run: npm ci
      - name: Build the Electron app
        run: npm run electron-linux
      - name: Zip
        run: cd .build; for i in test-electron-packager-*; do zip -r "$i.zip" "$i"; done; cd ../;
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-linux
          include-hidden-files: true
          path: .build/*.zip
          if-no-files-found: error
