name: Build and publish artifacts

on: workflow_dispatch

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Build artifacts
    uses: ./.github/workflows/build.yml

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .build
          pattern: build-artifacts-*
          merge-multiple: true
      - name: List files
        run: ls -la .build
      - name: Upload to release
        env:
          GH_REF_NAME: ${{ github.ref_name }}
        run: |
          for i in .build/*.zip; do gh release upload "1.0.0" "$i" --clobber; done;

